# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3705a971d820fdeb8246524b64318aa72511f41e202a49c10866af89757b8843b5a7ece07b1b09fa1f26623417e0c46dcbd91a956d60f74011aeaf2e57daec8d

test:
  secret_key_base: 8854f209a102d0be5efd912b8190917d48935aa5e4db989518a432dac59f8e90aac5366709528762213b4828a1d7f01efc8d924482cdd3dddbb37a295daf4759

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
